# Generated by Django 5.1.3 on 2024-11-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
